language: generic

env:
  - R_LIBS_USER=~/R

addons:
  apt:
    packages:
      - r-base

install:
  - mkdir -p ~/R

script:
  - cd r && sudo make setup && make test

after_success:
  - Rscript -e 'covr::codecov()'
