language: generic

env:
  - R_LIBS_USER=~/R

addons:
  apt:
    sources:
      - sourceline: 'deb https://cran.rstudio.com/bin/linux/ubuntu trusty/'
    packages:
      - r-base

install:
  - mkdir -p ~/R

script:
  - cd r && sudo make setup && make test

after_success:
  - Rscript -e 'covr::codecov()'
