language: generic

cache:
  directories:
    - node_modules

addons:
  apt:
    sources:
      - sourceline: 'deb https://deb.nodesource.com/node_8.x trusty main'
    packages:
      - nodejs

install:
  - make install

script:
  - make lint
  - make cover
  - make build

after_success:
  - bash <(curl -s https://codecov.io/bash)
