language: generic

env:
  - R_LIBS_USER=~/R

cache:
  directories:
    - node_modules
    - ~/R

addons:
  apt:
    sources:
      - sourceline: 'deb https://deb.nodesource.com/node_8.x trusty main'
      - sourceline: 'deb https://cran.rstudio.com/bin/linux/ubuntu trusty/'
    packages:
      - nodejs
      - r-base
      - r-base-dev

install:
  - cd js && npm install
  - mkdir -p ~/R && Rscript -e 'install.packages(c("lintr", "testthat", "covr"), lib="~/R", repo="http://cloud.r-project.org/")'

script:
  - (cd js; npm test)
  - Rscript -e 'lintr::lint_package("r")' 
  - R CMD check --no-manual r

after_success:
  - Rscript -e 'covr::codecov("r", relative_path=FALSE)'
